version: '3.8'

services:
  frontend:
    build:
      context: ./Tubes2_FE_Chibye
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Tubes2_BE_Chibye
    ports:
      - "8080:8080"